[workspace]

members = [
    "components/measure",
    "components/cpu",
    "components/disk",
    "components/memory",
    "components/network",
    "components/benchmark",
    "components/scheduler",
    "components/cost_flow",
    "components/scheduler_agent",
]