[workspace]

members = [
    "components/measure",
    "components/cpu",
    "components/disk",
    "components/memory",
    "components/network",
    "components/benchmark",
    "components/workload/factor",
    "components/scheduler",
]