[package]
name = "cpu"
version = "0.1.0"
authors = ["Peter Hrvola <peter.hrvola@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.3.0"
clap = "2.33.0"
